/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EngagementRequest = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const CommunitySegment = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const FocusArea = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const GlobalInitiative = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEngagementRequests' : IDL.Func(
      [],
      [IDL.Vec(EngagementRequest)],
      ['query'],
    ),
  'getCommunitySegments' : IDL.Func([], [IDL.Vec(CommunitySegment)], ['query']),
  'getFocusAreas' : IDL.Func([], [IDL.Vec(FocusArea)], ['query']),
  'getGlobalInitiatives' : IDL.Func([], [IDL.Vec(GlobalInitiative)], ['query']),
  'getProfileInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'bio' : IDL.Text,
          'titles' : IDL.Text,
          'visionStatement' : IDL.Text,
          'name' : IDL.Text,
          'credentials' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitEngagementRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EngagementRequest = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const CommunitySegment = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const FocusArea = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const GlobalInitiative = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEngagementRequests' : IDL.Func(
        [],
        [IDL.Vec(EngagementRequest)],
        ['query'],
      ),
    'getCommunitySegments' : IDL.Func(
        [],
        [IDL.Vec(CommunitySegment)],
        ['query'],
      ),
    'getFocusAreas' : IDL.Func([], [IDL.Vec(FocusArea)], ['query']),
    'getGlobalInitiatives' : IDL.Func(
        [],
        [IDL.Vec(GlobalInitiative)],
        ['query'],
      ),
    'getProfileInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'bio' : IDL.Text,
            'titles' : IDL.Text,
            'visionStatement' : IDL.Text,
            'name' : IDL.Text,
            'credentials' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitEngagementRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };