/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunitySegment { 'title' : string, 'description' : string }
export interface EngagementRequest {
  'name' : string,
  'role' : string,
  'sector' : string,
  'email' : string,
  'message' : string,
}
export interface FocusArea {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface GlobalInitiative {
  'status' : string,
  'title' : string,
  'description' : string,
}
export interface Testimonial {
  'role' : string,
  'quote' : string,
  'author' : string,
  'organization' : string,
}
export interface _SERVICE {
  'getAllEngagementRequests' : ActorMethod<[], Array<EngagementRequest>>,
  'getCommunitySegments' : ActorMethod<[], Array<CommunitySegment>>,
  'getFocusAreas' : ActorMethod<[], Array<FocusArea>>,
  'getGlobalInitiatives' : ActorMethod<[], Array<GlobalInitiative>>,
  'getProfileInfo' : ActorMethod<
    [],
    {
      'bio' : string,
      'titles' : string,
      'visionStatement' : string,
      'name' : string,
      'credentials' : string,
    }
  >,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitEngagementRequest' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];